### ISSUE TITLE
ArgumentError thrown at DAQmxFunctions->mafunction

### ISSUE THREAD

**Issue by mbiskach** [clade/PyDAQmx#7]
I'm attempting to run PyDAQmx on Python 3.3 (32-bit), on a Windows 7 machine with LabVIEW 8.6 (32-bit) and NI-DAQ (9.2.1) installed.

During PyDAQmx installation, I had to use python 2to3.py -w . to upgrade all *.py files on latest version of source code downloaded from Github (version 1.2.5.2). I wonder if anyone else has got PyDAQmx installed and running for Python 3.3 using this approach? I had issues getting all of the modules in the PyDAQmx package installed using the published Python 3 install instructions.

The NIDAQmx.h version is Copyright 2003-2010.

After attempting to run any of the examples I get the same error message:

```
Traceback (most recent call last):
File "example.py", line 9, in <module>
analog_input.CreateAIVoltageChan("cDAQ1Mod1/ai0","",DAQmx_Val_Cfg_Default,-10.0,10.0,DAQmx_Val_Volts,None)
File "<string>", line 3, in CreateAIVoltageChan
File "<string>", line 2, in function
File "C:\Python33\lib\site-packages\pydaqmx-1.2.5.2-py3.3.egg\PyDAQmx\DAQmxFunctions.py", line 23, in mafunction
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

example.py

``` python
from PyDAQmx import *
import numpy

analog_input = Task()
read = int32()
data = numpy.zeros((1000,), dtype=numpy.float64)

# DAQmx Configure Code
analog_input.CreateAIVoltageChan("cDAQ1Mod1/ai0","",DAQmx_Val_Cfg_Default,-10.0,10.0,DAQmx_Val_Volts,None)
analog_input.CfgSampClkTiming("",10000.0,DAQmx_Val_Rising,DAQmx_Val_FiniteSamps,1000)

# DAQmx Start Code
analog_input.StartTask()

# DAQmx Read Code
analog_input.ReadAnalogF64(1000,10.0,DAQmx_Val_GroupByChannel,data,1000,byref(read),None)

print("Acquired %d points"%read.value)
```

It's tough for me to tell if this error is due to improper PyDAQmx package setup for Python 3...

Will attempt to install and run package on Python 2.7 to see if error still exists for me.

**Comment by fallen** [comment]
I had the same issue about byte strings, maybe indeed it can be written somewhere in documentation :)
